In [1]:
import pandas as pd

In [2]:
cluster_df = pd.read_csv('/cluster2/huanglab/jiamao/Project/HumanSpinalCord/Work/P3/ST/multimapping/GW16/cluster_df_add.atac.txt', sep='\t', index_col=0)
cluster_df = cluster_df.sort_index()
cluster_df.head()

,UMAP-1,UMAP-2,cluster,n_fragment,frac_dup,frac_mito,tsse,enhancer_frac,promoter_frac,tsse_bk,...,S.Score,G2M.Score,Phase,RNA_snn_res.0.9,seurat_clusters,pANN_0.25_0.09_1937,DF.classifications_0.25_0.09_1937,sex,sample,cell_name
AAACAGCCAATAATGG-1,-5.015583,5.735539,Microgila,5672,0.360973,0.0,13.149351,0.162906,0.316819,13.149351,...,-0.017687,-0.017604,G1,16,16,0.192688,Singlet,male,spinalcord-rna-GW16,Microgila
AAACAGCCAATAGCAA-1,2.702181,-5.422496,FP/Ependymal,4625,0.358263,0.0,19.886364,0.191135,0.442162,19.886364,...,-0.016086,0.002110,G2M,12,12,0.295484,Singlet,male,spinalcord-rna-GW16,FP/Ependymal
AAACAGCCACCTCAGG-1,11.119884,2.224765,COP,8892,0.353920,0.0,8.253589,0.189159,0.247638,8.253589,...,-0.050263,0.042021,G2M,6,6,0.218065,Singlet,male,spinalcord-rna-GW16,COP
AAACAGCCACCTGGTG-1,-5.580664,5.723388,Microgila,5571,0.361636,0.0,20.557851,0.141447,0.389876,20.557851,...,-0.032145,-0.000688,G1,16,16,0.161720,Singlet,male,spinalcord-rna-GW16,Microgila
AAACAGCCAGGATGGC-1,10.709215,2.331022,COP,3113,0.367662,0.0,8.181818,0.189528,0.267266,8.181818,...,0.033592,-0.000586,S,6,6,0.113548,Singlet,male,spinalcord-rna-GW16,COP

In [3]:
rna_anno = pd.read_csv('/cluster2/huanglab/jiamao/Project/HumanSpinalCord/Work/P3/ST/multimapping/GW16/rna_anno.csv', index_col=0)
rna_anno.head()

                       cell_name
AAACAGCCAATAATGG-1     Microgila
AAACAGCCAATAGCAA-1  FP/Ependymal
AAACAGCCACCTCAGG-1           COP
AAACAGCCACCTGGTG-1     Microgila
AAACAGCCAGCCTTGG-1         APC-2

In [4]:
common_indices = cluster_df.index.intersection(rna_anno.index)

link_atac_matrix = pd.DataFrame({
    'id_atac': common_indices,
    'id_rna': common_indices,
    'cluster_rna': rna_anno.loc[common_indices, 'cell_name']
})
link_atac_matrix.head()

                               id_atac              id_rna   cluster_rna
AAACAGCCAATAATGG-1  AAACAGCCAATAATGG-1  AAACAGCCAATAATGG-1     Microgila
AAACAGCCAATAGCAA-1  AAACAGCCAATAGCAA-1  AAACAGCCAATAGCAA-1  FP/Ependymal
AAACAGCCACCTCAGG-1  AAACAGCCACCTCAGG-1  AAACAGCCACCTCAGG-1           COP
AAACAGCCACCTGGTG-1  AAACAGCCACCTGGTG-1  AAACAGCCACCTGGTG-1     Microgila
AAACAGCCAGGATGGC-1  AAACAGCCAGGATGGC-1  AAACAGCCAGGATGGC-1           COP

In [5]:
link_atac_matrix.to_csv("/cluster2/huanglab/jiamao/Project/HumanSpinalCord/Work/P3/ST/multimapping/GW16/link_atac_matrix.csv", index=False)

In [6]:
atac_umap = cluster_df[['UMAP-1', 'UMAP-2']].rename(columns={'UMAP-1': 'UMAP_1', 'UMAP-2': 'UMAP_2'})
atac_umap.head()

                       UMAP_1    UMAP_2
AAACAGCCAATAATGG-1  -5.015583  5.735539
AAACAGCCAATAGCAA-1   2.702181 -5.422496
AAACAGCCACCTCAGG-1  11.119884  2.224765
AAACAGCCACCTGGTG-1  -5.580664  5.723388
AAACAGCCAGGATGGC-1  10.709215  2.331022

In [7]:
atac_umap.to_csv("/cluster2/huanglab/jiamao/Project/HumanSpinalCord/Work/P3/ST/multimapping/GW16/atac_umap.csv", index=True)